var h=e=>{throw TypeError(e)};var L=(e,t,n)=>t.has(e)||h("Cannot "+n);var m=(e,t,n)=>(L(e,t,"read from private field"),n?n.call(e):t.get(e)),p=(e,t,n)=>t.has(e)?h("Cannot add the same private member more than once"):t instanceof WeakSet?t.add(e):t.set(e,n);(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const i of document.querySelectorAll('link[rel="modulepreload"]'))a(i);new MutationObserver(i=>{for(const s of i)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function n(i){const s={};return i.integrity&&(s.integrity=i.integrity),i.referrerPolicy&&(s.referrerPolicy=i.referrerPolicy),i.crossOrigin==="use-credentials"?s.credentials="include":i.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(i){if(i.ep)return;i.ep=!0;const s=n(i);fetch(i.href,s)}})();var u,d;class S{constructor(){p(this,u,"3vLlhLsn5MSlQI96Cy78HBPNhef1xnsS");p(this,d,"https://app.ticketmaster.com/discovery/v2/events.json");this.page=0,this.pageSize=12,this.searchQuery="",this.country=""}async fetchEvents(){const t=new URLSearchParams({apikey:m(this,u),page:this.page,size:this.pageSize,keyword:this.searchQuery}),n=`${m(this,d)}?${t}&classificationName=music`,a=await fetch(n);if(!a.ok)throw new Error("Failed to fetch events");return a.json()}}u=new WeakMap,d=new WeakMap;function b(e){return e.map(n=>{var l,f;const a=((l=n.images[0])==null?void 0:l.url)||"",i=n.name||"No name available",s=n.dates.start.localDate||"Unknown date",o=((f=n._embedded)==null?void 0:f.venues[0].name)||"Unknown location",r=n.url||"#";return`
        <li class="cards__item">
                <img src="${a}" alt="${i}" class="cards__item__img">
                <h2 class="cards__item__title">
                    ${i}
                </h2>
                <p class="cards__item__date">${s}</p>
                <a href="${r}" class="cards__item__location__link">
                    <svg class="location__item__icon">
                        <use href="../img/icons/sprite.svg#icon-location"> </use>
                    </svg>

                   ${o} </a>
            </li>
      `}).join("")}function E(e,t,n){const a=document.querySelector(".pagination__list");a.innerHTML="";const s=U(e,t).map(r=>r==="..."?`<li class="pagination__list__item">
                <span class="pagination__dots">...</span>
            </li>`:` <li class="pagination__list__item">
                <button class="pagination__list__button ${r===t?"active":""}" data-page="${r}">${r+1}</button>
            </li>`).join("");a.insertAdjacentHTML("beforeend",s),a.addEventListener("click",o);function o(r){if(r.target.tagName!=="BUTTON")return;const l=Number(r.target.dataset.page);l!==t&&n(l)}}function U(e,t){const n=[];if(e<=5)for(let i=0;i<e;i++)n.push(i);else{t>1&&n.push(0),t>2&&n.push("...");const i=Math.max(0,t-1),s=Math.min(e,t+2);for(let o=i;o<s;o++)n.push(o);t<e-3&&n.push("..."),t<e-1&&n.push(e-1)}return n}const g=document.querySelector(".cards__list"),w=document.querySelector(".pagination__list"),k=document.getElementById("header__form"),M=document.getElementById("search-input"),c=new S;_();k.addEventListener("submit",$);async function $(e){e.preventDefault(),c.searchQuery=M.value.trim(),c.page=0,y(),N(),await _()}async function _(){var e;try{const t=await c.fetchEvents(),n=((e=t._embedded)==null?void 0:e.events)||[],a=b(n);g.insertAdjacentHTML("beforeend",a);const i=t.page.totalPages;console.log("Total Pages:",i,"Current Page:",c.page),E(i,c.page,B)}catch(t){console.error(t)}}function y(){g.innerHTML=""}function B(e){e!==c.page&&(c.page=e,y(),_())}function N(){w.innerHTML=""}const A=[{en:"Austria"},{en:"Belgium"},{en:"Bosnia and Herzegovina"},{en:"United Kingdom"},{en:"Hungary"},{en:"Germany"},{en:"Georgia"},{en:"Denmark"},{en:"Ireland"},{en:"Spain"},{en:"Italy"},{en:"Canada"},{en:"Latvia"},{en:"Lithuania"},{en:"Netherlands"},{en:"Norway"},{en:"Poland"},{en:"Portugal"},{en:"South Korea"},{en:"Romania"},{en:"Serbia"},{en:"Slovakia"},{en:"Slovenia"},{en:"United States"},{en:"Finland"},{en:"France"},{en:"Croatia"},{en:"Czech Republic"},{en:"Switzerland"},{en:"Sweden"},{en:"Estonia"},{en:"South Africa"},{en:"Japan"}],v=document.getElementById("header__form__country__select"),C=document.querySelector(".header__form__country__button-text"),I=A.map(e=>`
        <option class='header__form__country__option' value="${e.en}">${e.en}</option>
    `).join("");v.insertAdjacentHTML("beforeend",I);v.addEventListener("change",T);function T(e){const t=e.target.value;C.textContent=t}
//# sourceMappingURL=index.js.map
